### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by owen800q** [Lewage59/bili-video#4]
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                             2:07:07 PM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/config.js:255:39)
    at Config.getConfigHierarchy (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/config.js:329:29)
    at processText (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (/Users/kwan/Programming/Javascript/vue/open-source-projects/bili-video/node_modules/eslint-loader/index.js:273:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Comment by owen800q** [comment]
@Lewage59

**Comment by Lewage59** [comment]
@owen800q i uploaded some configuration files to solve it

**Comment by owen800q** [comment]
@Lewage59 thanks bro, it works now, this project is really useful for me to learn Vue.. Hopfully migrate to vue cli in future if you have spare time.
